kind: Service
apiVersion: v1

metadata:
  name: k8s-intro
  labels:
    app: k8s-intro

spec:
  type: NodePort

  selector:
    app: k8s-intro

  ports:
    - name: k8s-intro-port
      protocol: TCP
      port: 3000
