kind: Deployment
apiVersion: apps/v1

metadata:
  labels:
    app: k8s-intro
  name: k8s-intro

spec:
  replicas: 1

  selector:
    matchLabels:
      app: k8s-intro

  template:
    metadata:
      labels:
        app: k8s-intro

    spec:
      containers:
      - image: waduhek/k8s-intro:latest
        name: k8s-intro
