kind: Service
apiVersion: v1

metadata:
  name: redis-master
  labels:
    app: redis
    type: master

spec:
  type: ClusterIP

  selector:
    app: redis
    type: master

  ports:
    - port: 6379
      name: redis-master-port
      protocol: TCP
