name: Check for formatting errors

on:
  pull_request:
    branches:
      - main

jobs:
  check-formatting:
    name: Check for formatting issues
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Check for formatting issues
        run: test -z $(gofmt -l .)

  test-build:
    name: Build the development image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v4
        with:
          push: false
          target: dev
